In [1]:
import pandas as pd
tabs = pd.read_csv('EDA_PROJECT_MAIN.csv')

In [95]:
tabs.to_csv('EDA_PROJECT_MAIN.csv')
tabs.to_excel('EDA_PROJECT_MAIN.xlsx')

In [38]:
tabs = tabs.drop([363]).reset_index(drop=True)

In [57]:
tabs['Review'] = tabs['Review'].fillna("0")

In [58]:
tabs["Review"] = tabs["Review"].astype("int")

In [46]:
new_df = tabs[['Brand', 'Colour']]

In [47]:
new_df

       Brand         Colour
0      REDMI  Graphite Grey
1    Samsung       Graphite
2       POCO    Cobalt Blue
3    Samsung           Navy
4    Samsung           Navy
..       ...            ...
401  Samsung       GRAPHITE
402  Samsung         Silver
403  Samsung           Navy
404  Samsung       Graphite
405  Samsung           Navy

[406 rows x 2 columns]

In [49]:
tabs[tabs['Colour'].isna()]

,Unnamed: 0,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
67,67,Samsung Galaxy Tab S10 Ultra,124999,12,4.5,135,14.0,14.6,11200,NaN,Android 14,Samsung
87,87,Samsung Galaxy Tab S10 Ultra,113999,12,4.5,135,14.0,14.6,11200,NaN,Android 14,Samsung
106,106,Samsung Galaxy Tab S10 Ultra,124999,12,4.5,135,14.0,14.6,11200,NaN,Android 14,Samsung
157,157,Samsung Galaxy Tab S10 Ultra,113999,12,4.5,135,14.0,14.6,11200,NaN,Android 14,Samsung
172,172,Samsung Galaxy Tab S10 Ultra,124999,12,4.5,135,14.0,14.6,11200,NaN,Android 14,Samsung
...,...,...,...,...,...,...,...,...,...,...,...,...
394,395,Apple ipad Mini,57939,0,4.6,5592,796.0,7.9,5078,NaN,iPadOS 14,Apple
395,396,Apple ipad Mini,45900,0,4.6,5592,796.0,7.9,5078,NaN,iPadOS 14,Apple
396,397,Apple ipad Mini,45900,0,4.6,5592,796.0,7.9,5078,NaN,iPadOS 14,Apple
397,398,Apple iPad Air,76979,0,4.7,9305,640.0,10.9,7606,NaN,iPadOS 14,Apple
398,399,Infinix XPAD LTE,11999,4,4.4,2555,273.0,11.0,7000,NaN,Android 14,Infinix

In [92]:
tabs[tabs['Ram']==0]

Empty DataFrame
Columns: [Unnamed: 0, Product_name, Price, Ram, Rating, Count_Rating, Review, Inch, Battery, Colour, Android_IOS, Brand]
Index: []

In [65]:
tabs.loc[tabs['Product_name'] ==  'Apple iPad','Ram'] = 4
tabs.loc[tabs['Product_name'] ==  'Apple 2024 iPad Pro','Ram'] = 12
tabs.loc[tabs['Product_name'] ==  'Apple 2022 iPad Pro','Ram'] = 16
tabs.loc[tabs['Product_name'] ==  'Apple iPad mini','Ram'] = 4
tabs.loc[tabs['Product_name'] ==  'Apple ipad Mini','Ram'] = 3
tabs.loc[tabs['Product_name'] ==  'Apple iPad Air','Ram'] = 4
tabs.loc[tabs['Product_name'] ==  'Apple 2024 iPad Mini','Ram'] = 8
tabs.loc[tabs['Product_name'] ==  'Apple 2025 iPad Air','Ram'] = 8
tabs.loc[tabs['Product_name'] ==  'Apple 2024 iPad Air','Ram'] = 8
tabs.loc[tabs['Product_name'] ==  'Apple 2025 iPad','Ram'] = 6
tabs.loc[tabs['Product_name'] ==  'Samsung Galaxy M17 5G','Ram'] = 8
tabs.loc[tabs['Product_name'] ==  'Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838','Ram'] = 8

In [60]:
tabs['Ram'].isna().sum()

np.int64(0)

In [22]:
# iOS iPadOS 18
# DRUMSTONE LearnTab 7-Inch Kids Learning Tablet
# Oxygen OS 15.0.1
# Android Oxygen OS 13.2
# Chrome OS
# Android Oxygen 15
# Android Oxygen Android 15
# Android v9 Pie


tabs.loc[tabs['Product_name'] ==  'Apple 2024 iPad Mini','Android_IOS'] = 'iOS iPadOS 18'
tabs.loc[tabs['Product_name'] ==  'DRUMSTONE LearnTab 7-Inch Kids Learning Tablet','Android_IOS'] = 'Android'
tabs.loc[tabs['Product_name'] ==  'OnePlus Pad Lite','Android_IOS'] = 'Oxygen OS 15.0.1'
tabs.loc[tabs['Product_name'] ==  'OnePlus Pad Go','Android_IOS'] = 'Android Oxygen OS 13.2'
tabs.loc[tabs['Product_name'] ==  'Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838','Android_IOS'] = 'Chrome OS'
tabs.loc[tabs['Product_name'] ==  'Samsung M36 5G','Android_IOS'] = 'Android Oxygen 15'
tabs.loc[tabs['Product_name'] ==  'Samsung Galaxy M17 5G','Android_IOS'] = 'Android Oxygen Android 15'
tabs.loc[tabs['Product_name'] ==  'iball iTAB BizniZ Mini','Android_IOS'] = 'Android v9 Pie'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    406 non-null    int64
 1   Product_name  406 non-null    object
 2   Price         406 non-null    int64
 3   Ram           406 non-null    int64
 4   Rating        406 non-null    float64
 5   Count_Rating  406 non-null    int64
 6   Review        406 non-null    int64
 7   Inch          406 non-null    float64
 8   Battery       406 non-null    int64
 9   Colour        345 non-null    object
 10  Android_IOS   406 non-null    object
 11  Brand         406 non-null    object
dtypes: float64(2), int64(6), object(4)
memory usage: 38.2+ KB

In [2]:
tabs

,Unnamed: 0,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS
0,0,REDMI Pad Pro 5G,"₹25,999",8 GB,4.4,"6,726",432,12.1,10000.0,Graphite Grey,Android 14
1,1,REDMI Pad Pro 5G,"₹23,999",8 GB,4.4,"6,726",432,12.1,10000.0,Quick Silver,Android 14
2,2,POCO Pad 5G,"₹21,999",8 GB,4.4,"9,167",749,12.1,10000.0,Cobalt Blue,Android 14
3,3,REDMI Pad Pro 5G,"₹23,999",8 GB,4.4,"6,726",432,12.1,10000.0,Graphite Grey,Android 14
4,4,Samsung Galaxy Tab A9+,"₹21,999",8 GB,4.5,"38,428","1,470",11.0,7040.0,Graphite,Android 12
...,...,...,...,...,...,...,...,...,...,...,...
403,403,Samsung Galaxy Tab A9+,"₹15,950",4 GB,4.5,"38,428","1,470",11.0,5100.0,Silver,Android 12
404,404,Huawei MatePad T8 LTE,"₹6,999",2 GB,3.8,474,44,NaN,5100.0,NaN,Android 10
405,405,Samsung Galaxy Tab S9 FE+,"₹45,999",12 GB,4.6,"24,796","1,051",12.4,10090.0,Lavender,Android 12
406,406,Samsung Galaxy Tab A9+,"₹16,999",8 GB,4.5,"38,428","1,470",11.0,5100.0,Navy,Android 12
407,407,Samsung Galaxy Tab S9 FE,"₹25,999",6 GB,4.5,"4,409",228,10.9,10090.0,Lavender,Android 12